name: Keep Render Awake

on:
  schedule:
    - cron: "*/5 * * * *"   # runs every 10 minutes
  workflow_dispatch:         # lets you trigger manually

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render App
        run: |
          curl -s https://lms-web-by-ganesh.onrender.com/health > /dev/null
